---
title: "limma"
author: "handy"
date: "2025-12-14"
output: html_document
---

```{r}
library(openxlsx)
data <- read.xlsx("GSE279750.xlsx")
head(data)
```

```{r warning=FALSE}
library(limma)
library(Biobase)
```

```{r}
# 读取表达矩阵
# 后续分析需要矩阵格式，此处把基因名用作行名
expr <- data[,-1]
rownames(expr) <- data[,1]
# 表达矩阵的列名作为样本信息的行名
metadata  <- data.frame(group = rep(c("NR","R"),c(4,6)))
rownames(metadata) <- colnames(expr)
metadata$group <- factor(metadata$group)
```

```{r}
# 创建设计矩阵
design <- model.matrix(~0 + metadata $group)
metadata$group <- factor(metadata$group, levels = c("NR", "R"))
colnames(design) <- levels(metadata$group)
print(design)
```

```{r}
# 创建eSet,需要Biobase包，assayData需要是矩阵格式的
pheno_data <- new("AnnotatedDataFrame", data = metadata)
eset <- ExpressionSet(assayData = as.matrix(expr), phenoData = pheno_data)

# 数据标准化（可选）
eset <- normalizeBetweenArrays(eset)

# 拟合线性模型
fit <- lmFit(exprs(eset), design)

# 创建比较矩阵
contrast_matrix <- makeContrasts(R - NR, levels = design)
fit2 <- contrasts.fit(fit, contrast_matrix)
# 贝叶斯检验
fit2 <- eBayes(fit2)

# 提取差异分析结果
results <- topTable(fit2, adjust = "BH", number = Inf)
head(results)

# 保存
save(results, file = "differential_expression_results.Rdata")
```
